
var Lang = {
    'LTitle': "Pakpobox",
    'LConnectError': 'Server Error',
    'LSystemError': 'Systerm Error',
    'LUsernamePlaceholer': 'Email/Phone/LoginName',
    'LUPasswordPlaceholer': 'Password',
    'LLoginSubmit': 'login',
    'LContratUs': 'Connect Us',
    'LForgetPassword': 'Forget Password？',
    'LValidation': 'Validation',
    'LResetPassword': 'Reset',
    'LValidationTips': 'Please put your binding infomation for Validation：',
    'LValitaionSubmit': 'Validate',
    'LValidationResultTips': 'Validate Successfully！Please check your random in your email！',
    'LValitaionResultButton': 'Return Login',
    'LLogout': 'Logout',

    'LUserTypeRoot': 'Super Admin',
    'LUserTypeManager': 'Manager',
    'LUserTypeOprator': 'Operator',
    'LUserTypeLogistics': 'Courier',
    'LUserTypeOpratorAdmin': 'OperatorAdmin',
    'LUserTypeLogisticsAdmin': 'CourierAdmin',

    'LLoginname': 'UserName',
    'LUsername': 'NickName',
    'LPhoneNumber': 'PhoneNumber',
    'LCompany': 'Company',
    'LRole': 'Role',
    'LCompanyName': 'Company Name',


    'LUpdatePassword': 'Password',
    'LOldPassword': 'OldPassword',
    'LNewPassword': 'NewPassword',
    'LReNewPassword': 'ReNewPassword',
    'LPasswordInconsistent': 'Password Inconsistent!',
    'LPasswordSuccess': 'Reset Successfully！Go to homepage...',

    'LAll': 'All',

    'LLevel': 'Level',
    'LLevelOne': 'Level1',
    'LLevelTwo': 'Level2',
    'LLevelThree': 'Level3',
    'LLevelFour': 'Level4',
    'LLevelFive': 'Level5',

    'LRole': 'Role',
    'LOperatorAdmin': 'Operator Admin',
    'LOperatorUser': 'Operator User',
    'LLogisticsAdmin': 'Logistics Admin',
    'LLogisticsUser': 'Logistics User',
    'LRootUser': 'Super Admin',

    'LStatus': 'Status',
    'LStatusOn': 'Open',
    'LStatusOff': 'Disable',

    'LNumber': 'Number',
    'LName': 'Name',
    'LCompanyNumber':'Company Number',
    'LSearch': 'Query',
    'LPhoneNum': 'TakePhone',
    'LTime': 'Time&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;',
    'LTimeStore': 'Store Time',
    'LTimeStatistics': 'Statistics Time',
    'LTimeTake': 'Take Time',
    'LEcommerce': 'Choose Ecommerce',
    'LStatisticsNote':'(Note: the default take statistical records for 30 days, if you need other time please choose statistical time)',

    'LOperatorInfo': 'Operator ',
    'LLinkmanInfo': 'Linkman ',
    'LOperatorInfoTips': 'Please confirm your company info',
    'LLinkmanInfoTips':'Please confirm your linkman info',
    'LOperatorNamePlaceholder': 'Please type your company info',
    'LOperatorParentPlaceholder': 'Please type your parent company info',

    //新增物流公司
    'LLogisticsInfo': 'Logistics Info',
    'LLogisticsInfoTips': 'Please confirm your company info',
    'LLogisticsNamePlaceholder': 'Please type your company info',
    'LLogisticsParentPlaceholder': 'Please type your parent company info',

    //新增人员信息
    'LPeopleInfo': ' People Info',
    'LPeopleType':' People Type',

    //人员信息详情
    'LPeopleInfoName': 'Name',
    'LPeopleInfoPhone': 'Phone',
    'LPeopleInfoWallets': 'Wallets',


    'LClose': 'Close',
    'LApply': 'Apply',
    'LReset': 'Reset',
    'LCancel': 'Cancel',
    'LNext': 'Next',
    'LSubmit': 'Submit',
    'LSubmitLoading': 'Submit...',
    'LSubmitValidate': 'Validate',
    'LSubmitValidating': 'Validating...',

    'LExpressInfo': 'Express Info',
    'LExpressStatuStoring': 'need Store',
    'LExpressStatuStore': 'stored',
    'LExpressStatuStored': 'taken',
    'LExpressStatuTimeout': 'timeout',
    'LExpressStatuCourierPickup': 'logistics pick',
    'LExpressStatuManagerPickup': 'operators pick',

    //table
    'LTableOrderSeq': 'sequence',
    'LTableOrderNumber': 'number',
    'LTableTakerPhone': 'takerPhone',
    'LTableCreateTime':'createTime',
    'LTableStoreTime': 'storeTime',
    'LTableTakeTime': 'takeTime',
    'LTablePakpoboxNum': 'BoxNum',
    'LTableValidationNum': 'validation',
    'LTableExpressStatu': 'Status',
    'LTableOperator': 'operator',
    'LTableDetails': 'Details',
    'LTableDelete' : 'Delete',
    'LTableDeleteOperator' : 'deleteOperator',
    'LTableDeleteAffirm' : 'Whether to delete information',
    'LTableDeleteCompanyAffirm' : 'Whether to delete company information',
    'LTableDeleteCompanySuccess': 'Company information deleted successfully',
    'LTableDeleteSuccess' : 'Personnel information deleted successfully',
    'LTableDeleteFailed': 'Personnel information delete failed',
    'LTablecCompanyDeleteFailed': 'Company information delete failed',
    'LChangeBoxState':'Enable and disable box state operation',
    'LChangeBoxStateAffirm' : 'Whether change the case status',
    'LExceptionBoxState':'Can not send the treasure chest of abnormal state',


    'LToEdit': 'To Edit',
    //运营商详情
    'LDetailOperatorsId': 'ID',
    'LDetailOperatorsName': 'NAME',
    'LDetailOperatorsParentName': 'PARENT',
    'LDetailLogisticsParentId': 'PARENT ID',
    'LDetailOperatorsParentId': 'PARENT ID',
    'LDetailOperatorsContact': 'CONTACT',
    'LDetailOperatorsContactPhone': 'PHONE',
    'LDetailOperatorsContactMail': 'MAIL',

    //运营商tableHead
    'LTableOperatorsSqe': 'seq',
    'LTableOperatorsName': 'Name',
    'LTableOperatorsLevel': 'Level',
    'LTableOperatorsParent': 'Parent',

    //物流公司详情
    'LDetailLogisticsInfo': 'LOGISTICS COMPANY INFO',
    'LDetailLogisticsId': 'ID',
    'LDetailLogisticsName': 'NAME',
    'LDetailLogisticsLevel': 'Logistics Level',
    'LDetailLogisticsParentName': 'PARENT',
    'LDetailLogisticsParentId': 'PARENT ID',
    'LDetailLogisticsContact': 'CONTACT',
    'LDetailLogisticsContactPhone': 'PHONE',
    'LDetailLogisticsContactMail': 'MAIL',

    //快件详情
    'LDetailPakpoboxMouth': 'Door Num',
    'LDetailPakpobox': 'Pakpobox Num',
    'LDetailPakpoboxName': 'Box Name',
    'LDetailTakerName': 'Taker Name',
    'LDetailTakerPhone': 'Taker phone',
    'LDetailStoreName': 'Receiver',
    'LDetailStorePhone': 'Receiver Phone',
    'LDetailCreateTime': 'Create Time',
    'LDetailStoreTime': 'Stored Time',
    'LDetailTakeTime': 'Get Time',
    'LDetailOverTime': 'Deadline',
    'LDetailStatu': 'Status',
    'LDetailValidation': 'Validation Number',
    'LDetailModify': 'Modify',
    'LDetailSure': 'Confirm',
    'LDetailIfReSendValidation': 'Whether confirm resend verification code？',
    'LDetailIfResetStatu': 'Whether Reset Statu？',
    'LDetailIfReSendSuccessfully': 'Send Validation Code Successfully',
    'LDetailIfReSendFailed': 'Send Validation Code Failed！',
    'LDetailIfDoReset': 'Reset Operator Is Send！',
    'LDetailReseting': 'Reseting。。。。',
    'LDetailIfResetSuccessfully': 'Reset Successfully！',
    'LDetailIfResetFailed': 'Reset Failed！',

    //人员信息详情
    'LDetailPeople': 'Store Time',
    'LDetailTakeTime': 'Get Time',
    'LDetailOverTime': 'Overdue Time',
    'LDetailStatu': 'status',
    'LDetailValidation': 'validation',
    'LDetailExpressMessage': 'Message Infomation',
    'LDetailMsgClick': 'Please Click',

    //导航
    'LNavBaseInfomation': 'Base Info',
    'LNavOperator': 'Operators',
    'LNavLogisticsCompany': 'LogisticsCompany',
    'LNavPeople': 'People Infomation',
    'LNavCourier': 'Courier',
    'LNavAccount': 'My Account',
    'LNavPakpobox': 'Pakpobox',
    'LNavPakpoboxMaintain': 'Maintain',
    'LNavPakpoboxManagement': 'Management',
    'LNavExpressManagement': 'Express',
    'LNavAbnomalExpress': 'AbnomalExpress',
    'LNavExpressManagementAll': 'courier',
    'LNavExpressManagementSend': 'Post',
    'LNavExpressManagementCustomertToStaff':'userInfo',
    'LNavExpressManagementBack': 'Return',
    'LNavExpressManagementImport': 'Import',
    'LNavAd': 'Ad',
    'LNavAdManagement': 'Management',
    'LNavStatic'     :  'Static',
    'LNavStaticExpress'     :  'Express Static',

    //快递员
    'LCourierCompany': 'Company',
    'LCourierName': 'Name',
    'LCourierPhone': 'Phone',
    'LLogisticsParentId': 'Parent company ID',
    'LLogisticsLevel': 'Level',
    'LLogisticsParent': 'Parent',
    'LLogisticsParentId': 'Parent Id',

    //拉取信息提示
    'LResponseEmpty': 'It is empty!',
    'LResponseError': 'OCCOUR ERROR',

    //新建按钮
    'LNewOperator': '+ Operator',
    'LNewLogistics': '+ Logistics',
    'LNewCourier': '+ People',

    //导出列表
    'LExportlist': 'Export',

    //操作列表
    'LSendValidation': 'send validation',
    'LResetStatus': 'reset',

    //分页
    'LGoto': 'Goto',
    'LPageNum':'Pages Number:',
    'LRecordNum':'Record Number:',

    //导入列表
    'LImportExpressType': 'Express Type',
    'LImportAll': 'All',
    'LImportCourier':'Courier Express',
    'LImportSend':'Send Express',
    'LImportReturn':'Return Express',
    'LImportExpress':'Import Express',
    'LImportModelDownload':'Download Import Model',
    //新增派宝箱
    'LPakpoboxOperator': 'Operator Id',
    'LPakpoboxName': 'Box Name',
    'LPakpoboxOrderNo': 'OrderNo',
    'LPakpoboxCurrencyUnit': 'Unit',
    'LPakpoboxZoneId': 'Zone',
    'LPakpoboxOverdueType': 'Overdue Tyte',
    'LPakpoboxOverdueTime': 'Overdue Time',
    'LPakpoboxSmsAccount': 'Sms Account',
    'LBoxSize': 'Box Size',
    'LPakpoboxInfoTips': 'Please Confirm infomation',
    'LFormNone': 'Lost Infomation！',

    //派宝箱维护
    'LPakpoboxStatus':'Status' ,
    'LPakpoboxRun':'RUN' ,
    'LPakpoboxStop':'STOP' ,
    'LPakpoboxException':'Exception' ,
    'LPakpoboxStopSuccess':'Box Run ',
    'LPakpoboxRunSuccess':'Box Stop ',
    'LPakpoboxOperator':'Operator Num' ,
    'LPakpoboxOperatorName':'Operator Name',
    'LPakpoboxName':'Pakpobox Name',
    'LPakpoboxStatus':'Pakpobox Status',
    'LPakpoboxDetail':'Pakpobox Management',
    'LPakpoboxNew':'+New',
    'LPakpoboxFreeNum': 'Pakpobox Free Num',
    'LPakpoboxNum':'Pakpobox Number',
    'LPakpoBoxInfoUpdate':'Pakpobox DoorUpdate',
    'LPakpoBoxDetail': 'Detail',
    'LPakpoBoxColumns': 'Not null columns between the two columns！',
    'LPakpoBoxSubmitRespose': 'Submit Successfullly，Wating ...！',
    'LPakpoBoxSubmitFail': 'Submmit Failed！',
    'LPakpoBoxSubmitBack': 'Confirm To Back！',
    'LPakpoBoxModifyMouthStatus': 'Modidfy Door Status',
    'LPakpoBoxEmpty': 'Empty',
    'LPakpoBoxLock': 'Lock',
    'LPakpoBoxFreeMouthNum': 'Free Door Num：',
    'LPakpoBoxRemoteUnlock': 'To confirm the following selected case door were unlocked remotely？',
    'LPakpoBoxStatusModify': 'To confirm for the following selected door state changes？',
    'LPakpoBoxPleaseChooseAMouth': 'Please Choose A Door',
    'LPakpoBoxForbiddenBusyStatus': 'Forbid the operator of busy door!',
    'LPakpoBoxGetMouthIdFailed': 'Get Door Id Failed!',
    'LPakpoBoxFree': 'Free',
    'LPakpoBoxBusy': 'Busy',
    'LPakpoBoxLocked': 'Locked',
    'LAddPakpoboxView': 'Go to add door view!',
    'LCopyCol':'CopyCol',

    //导入
    'LChooseFile':'Choose File',
    'LBeginUpload':'Upload',
    'LUploadGuide':'Guide',
    'LUploadStep1':'1.First ',
    'LUploadStep12':'，fill in the information according to the example',
    'LUploadStep2':'2. Click select files above, choose the file you want to import',
    'LUploadStep3':'3. Click start uploading, you can upload your files',
    'LWaitingUpload':'Waiting Upload....',
    'LUploading':'Uploading....',
    'LUploadingComplete':'Upload Complete',
    'LUploadingSuccess': 'Upload Success',
    'LUploadFailId':'Fail Id',
    'LUploadType':'Fail Type',
    'LUploadexisted':'Existed',
    'LUploadNotSure':'Not Sure',
    'LUploadArgError':'Arg Error',
    'LUploadFailCounts':'Records fail，',
    'LUploadFailContent':'Click here to export the failures',
    'LUploadError':'Upload Failed',
    'LPleaseChooseFile': 'Please choose file',

    'LStatisticsNameTime': 'Store Time',
    'LStatisticsNameType': 'Store Type',
    'LStatisticsDay1': 'First Day',
    'LStatisticsDay2': 'Second Day',
    'LStatisticsDay3': 'Third Day',
    'LStatisticsDayO': 'Overdue',
    'LStatisticsPer': '%',
    'LStatisticsMINI': 'MINI',
    'LStatisticsS': 'S',
    'LStatisticsM': 'M',
    'LStatisticsL': 'L',
    'LStatisticsXL': 'XL',
    'LStatisticsTotal': 'Combine',
    'LStatisticsExport': 'Import',
    'LPakpoboxEdit': 'Adjust Pakpobox',
    'LPakpoboxRemoteUnlock': 'Remote Unlock',
    'LPakpoboxChangeStatus': 'Modify Status',
    'LPakpoboxMouthId': 'Door ID',

    'LWaiting': 'Wait......',
    'LSuccess': 'Successful！',
    'LTips': 'Tips',
    'LStatusError': 'forbid do this for door on this status',

    'LTaskCOMMIT': 'Submit Successfully',
    'LTaskSUCCESS': 'Task Successful',
    'LTaskERROR': 'Task Error',


    'LPleaseChoose': 'Please Choose',
    'LNotEmpty': ' Cannot be Empty!',
    'LFormatError': 'Format Error!',
    'LInconformity': 'Inconformity!',
    'LMultiSelected': 'Selected',
    'LMultiSelectedAll': 'All Selected',
    'LExists':' already exists!',
    'LRename':' Please input again!',

    //短信列表
    'LSmsList': 'Message List',
    'LSmsStatus': 'status',
    'LSmsStatusReady': 'Ready',
    'LSmsStatusSuc': 'Success',
    'LSmsStatusFail': 'Failure',
    //广告
    'LBusinessPicChoose': 'Choose Picture...',
    'LBusinessPicAdd': 'Add',

    //逾期
    'LOverdueStatus': 'If Overdue',
    'LOverdueStatusOverdue': 'Overdue',
    'LOverdueStatusYes': 'OD',
    'LOverdueStatusNo': 'No',
    'LOverdueTimeReset': 'Choose Overdue Time',
    'LResetOverTime' : 'Reset Overdue Time',

    //电商名称
    'LElectronicCommerceName': 'ElectronicCommerceName',

    //errorcode
    //'LSUCCESS': '成功',
    'LParameterError': 'Parameter Error',
    'LNoJurisdiction': 'Access denied, have no jurisdiction',
    'LUnknownError': 'Unknown Error',
    //'LSystemError': '系统错误',
    'LLoginTimeout': 'login timeout',
    'LNotFindRepository': 'did not find repository',


    //快递员派件数报表
    'LMonday' : 'Mon',
    'LTuesday' : 'Tue',
    'LWednesday' : 'Wed',
    'LThursday' : 'Thu',
    'LFriday' : 'Fri',
    'LSaturday' : 'Sat',
    'LSunday' : 'Sun',
    'LExpressNumber' : 'ExpressNumber',

    //有格口被使用或者被锁定修改格口按钮不能点击
    'LNotModifyMouth' : 'Have door is “USED” or “LOCKED”,Do not modify the door!',

    //时区
    'LACT':'Australia/Darwin',
    'LAET':'Australia/Sydney',
    'LAGT':'America/Argentina/Buenos_Aires',
    'LART':'Africa/Cairo',
    'LAST':'America/Anchorage',
    'LBET':'America/Sao_Paulo',
    'LBST':'Asia/Dhaka',
    'LCAT':'America/St_Johns',
    'LCNT':'America/St_Johns',
    'LCST':'America/Chicago',
    'LCTT':'Asia/Shanghai',
    'LEAT':'Africa/Addis_Ababa',
    'LECT':'Europe/Paris',
    'LIET':'America/Indiana/Indianapolis',
    'LIST':'Asia/Kolkata',
    'LJST':'Asia/Tokyo',
    'LMIT':'Pacific/Apia',
    'LNET':'sia/Yerevan',
    'LNST':'Pacific/Auckland',
    'LPLT':'Asia/Karachi',
    'LPNT':'America/Phoenix',
    'LPRT':'America/Puerto_Rico',
    'LPST':'America/Los_Angeles',
    'LSST':'Pacific/Guadalcanal',
    'LVST':'Asia/Ho_Chi_Minh',


    //广告发布管理
    'LADEdit' :'Advertising editor',
    'LChooseADManager' :'Please select advertising pictures and upload to management',
    'LADLocationInfo' :'The location information of display advertising',
    'LChooseOprator' :'Choosing operator',
    'LChooseImg':'Choose Picture',
    'LUploadImgSuccess' :'Picture uploaded successfully',
    'LUploadADInfoSuccess' :'Advertising uploaded successfully',
    'LPleaseChooseADLocationInfo' :'Please select a picture position',
    'LPleaseChooseOprator' :'Please select on the operators', 

    //广告列表
    'LOperatorName' :'Operator',
    'LADPosition' :'Position',
    'LImgCreateTime' :'CreateTime',
    'LImgName' :'PicName',

    //错误提示
    //基本信息-运营商模块提示
    'LOperatorDeleteFailTips':'the company has box, can not be delete',
    'LLogisticsDeleteFailTips':'the company has the staff, can not be delete',
    'LCompanyNameExist':'company name already exists',
    'LCreateOutLimit':'Level out of limit',
    'LUpdateParentCompanyFail':'Exceed the lowest grade',
}

module.exports = Lang;