
var Lang = {
    'LTitle': "Pakpobox",
    'LConnectError': 'Server Error',
    'LSystemError': 'Systerm Error',
    'LUsernamePlaceholer': 'Email/Phone/LoginName',
    'LUPasswordPlaceholer': 'Password',
    'LLoginSubmit': 'login',
    'LContratUs': 'Connect Us',
    'LForgetPassword': 'Forget Password？',
    'LValidation': 'Validation',
    'LResetPassword': 'Reset',
    'LValidationTips': 'Please put your binding infomation for Validation：',
    'LValitaionSubmit': 'Validate',
    'LValidationResultTips': 'Validate Successfully！Please check your random in your email！',
    'LValitaionResultButton': 'Return Login',
    'LLogout': 'Logout',

    'LUserTypeRoot': 'Supper Admin',
    'LUserTypeManager': 'Manager',
    'LUserTypeOprator': 'Operator',
    'LUserTypeLogistics': 'Courier',
    'LUserTypeOpratorAdmin': 'OperatorAdmin',
    'LUserTypeLogisticsAdmin': 'CourierAdmin',

    'LLoginname': 'UserName',
    'LUsername': 'NickName',
    'LPhoneNumber': 'PhoneNumber',
    'LCompany': 'Company',
    'LRole': 'Role',
    'LCompanyName': 'Company Name',


    'LUpdatePassword': 'Password',
    'LOldPassword': 'OldPassword',
    'LNewPassword': 'NewPassword',
    'LReNewPassword': 'ReNewPassword',
    'LPasswordInconsistent': 'Password Inconsistent!',
    'LPasswordSuccess': 'Reset Successfully！Go to homepage...',

    'LAll': 'All',

    'LLevel': 'Level',
    'LLevelOne': 'Level1',
    'LLevelTwo': 'Level2',
    'LLevelThree': 'Level3',
    'LLevelFour': 'Level4',
    'LLevelFive': 'Level5',

    'LRole': 'Role',
    'LOperatorAdmin': 'Operator Admin',
    'LOperatorUser': 'Operator User',
    'LLogisticsAdmin': 'Logistics Admin',
    'LLogisticsUser': 'Logistics User',
    'LRootUser': 'Super Admin',

    'LStatus': 'Status',
    'LStatusOn': 'Open',
    'LStatusOff': 'Disable',

    'LNumber': 'Number',
    'LName': 'Name',
    'LCompanyNumber':'Company Number',
    'LSearch': 'Query',
    'LPhoneNum': 'TakePhone',
    'LTime': 'Time&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;',
    'LTimeStore': 'Store Time',
    'LTimeTake': 'Take Time',
    'LEcommerce': 'Choose Ecommerce',

    'LOperatorInfo': 'Operator ',
    'LLinkmanInfo': 'Linkman ',
    'LOperatorInfoTips': 'Please confirm your company info',
    'LOperatorNamePlaceholder': 'Please type your company info',
    'LOperatorParentPlaceholder': 'Please type your parent company info',

    //新增物流公司
    'LLogisticsInfo': 'Logistics Info',
    'LLogisticsInfoTips': 'Please confirm your company info',
    'LLogisticsNamePlaceholder': 'Please type your company info',
    'LLogisticsParentPlaceholder': 'Please type your parent company info',

    //新增人员信息
    'LPeopleInfo': 'People Info',
    'LPeopleType':'People Type',

    //人员信息详情
    'LPeopleInfoName': 'Name',
    'LPeopleInfoPhone': 'Phone',
    'LPeopleInfoWallets': 'Wallets',


    'LClose': 'Close',
    'LApply': 'Apply',
    'LReset': 'Reset',
    'LCancel': 'Cancel',
    'LNext': 'Next',
    'LSubmit': 'Submit',
    'LSubmitLoading': 'Submit...',
    'LSubmitValidate': 'Validate',
    'LSubmitValidating': 'Validating...',

    'LExpressInfo': 'Express Info',
    'LExpressStatuStoring': 'need Store',
    'LExpressStatuStore': 'stored',
    'LExpressStatuStored': 'got',
    'LExpressStatuTimeout': 'timeout',
    'LExpressStatuCourierPickup': 'courier pick',
    'LExpressStatuManagerPickup': 'manager pick',

    //table
    'LTableOrderSeq': 'sequence',
    'LTableOrderNumber': 'number',
    'LTableTakerPhone': 'takerPhone',
    'LTableStoreTime': 'storeTime',
    'LTableTakeTime': 'takeTime',
    'LTablePakpoboxNum': 'BoxNum',
    'LTableValidationNum': 'validation',
    'LTableExpressStatu': 'Status',
    'LTableOperator': 'operator',
    'LTableDetails': 'Details',

    'LToEdit': 'To Edit',
    //运营商详情
    'LDetailOperatorsId': 'ID',
    'LDetailOperatorsName': 'NAME',
    'LDetailLogisticsParentName': 'PARENT',
    'LDetailLogisticsParentId': 'PARENT ID',
    'LDetailOperatorsParentId': 'PARENT ID',
    'LDetailOperatorsContact': 'CONTACT',
    'LDetailOperatorsContactPhone': 'PHONE',
    'LDetailOperatorsContactMail': 'MAIL',

    //运营商tableHead
    'LTableOperatorsSqe': 'seq',
    'LTableOperatorsName': 'Name',
    'LTableOperatorsLevel': 'Level',
    'LTableOperatorsParent': 'Parent',

    //物流公司详情
    'LDetailLogisticsInfo': 'LOGISTICS COMPANY INFO',
    'LDetailLogisticsId': 'ID',
    'LDetailLogisticsName': 'NAME',
    'LDetailLogisticsLevel': 'Logistics Level',
    'LDetailLogisticsParentName': 'PARENT',
    'LDetailLogisticsParentId': 'PARENT ID',
    'LDetailLogisticsContact': 'CONTACT',
    'LDetailLogisticsContactPhone': 'PHONE',
    'LDetailLogisticsContactMail': 'MAIL',

    //快件详情
    'LDetailPakpoboxMouth': 'Mouth Num',
    'LDetailPakpobox': 'Pakpobox Num',
    'LDetailPakpoboxName': 'Box Name',
    'LDetailTakerName': 'Taker Name',
    'LDetailTakerPhone': 'Taker phone',
    'LDetailStoreName': 'Receiver',
    'LDetailStorePhone': 'Receiver Phone',
    'LDetailStoreTime': 'Stored Time',
    'LDetailTakeTime': 'Get Time',
    'LDetailOverTime': 'Deadline',
    'LDetailStatu': 'Status',
    'LDetailValidation': 'Validation Number',
    'LDetailModify': 'Modify',
    'LDetailSure': 'Confirm',
    'LDetailIfReSendValidation': 'Whether confirm resend verification code？',
    'LDetailIfResetStatu': 'Whether Reset Statu？',
    'LDetailIfReSendSuccessfully': 'Send Validation Code Successfully',
    'LDetailIfReSendFailed': 'Send Validation Code Failed！',
    'LDetailIfDoReset': 'Reset Operator Is Send！',
    'LDetailReseting': 'Reseting。。。。',
    'LDetailIfResetSuccessfully': 'Reset Successfully！',
    'LDetailIfResetFailed': 'Reset Failed！',

    //人员信息详情
    'LDetailPeople': 'Store Time',
    'LDetailTakeTime': 'Get Time',
    'LDetailOverTime': 'Overdue Time',
    'LDetailStatu': 'status',
    'LDetailValidation': 'validation',
    'LDetailExpressMessage': 'Message Infomation',
    'LDetailMsgClick': 'Please Click',

    //导航
    'LNavBaseInfomation': 'Base Info',
    'LNavOperator': 'Operators',
    'LNavLogisticsCompany': 'LogisticsCompany',
    'LNavPeople': 'People Infomation',
    'LNavCourier': 'Courier',
    'LNavAccount': 'My Account',
    'LNavPakpobox': 'Pakpobox',
    'LNavPakpoboxMaintain': 'Maintain',
    'LNavPakpoboxManagement': 'Management',
    'LNavExpressManagement': 'Express',
    'LNavAbnomalExpress': 'AbnomalExpress',
    'LNavExpressManagementAll': 'courier',
    'LNavExpressManagementSend': 'Post',
    'LNavExpressManagementBack': 'Return',
    'LNavExpressManagementImport': 'Import',
    'LNavAd': 'Ad',
    'LNavAdManagement': 'Management',
    'LNavStatic'     :  'Static',
    'LNavStaticExpress'     :  'Express Static',

    //快递员
    'LCourierCompany': 'Company',
    'LCourierName': 'Name',
    'LCourierPhone': 'Phone',
    'LLogisticsParentId': 'Parent company ID',
    'LLogisticsLevel': 'Level',
    'LLogisticsParent': 'Parent',
    'LLogisticsParentId': 'Parent Id',

    //拉取信息提示
    'LResponseEmpty': 'It is empty!',
    'LResponseError': 'OCCOUR ERROR',

    //新建按钮
    'LNewOperator': '+ Operator',
    'LNewLogistics': '+ Logistics',
    'LNewCourier': '+ People',

    //导出列表
    'LExportlist': 'Export',

    //操作列表
    'LSendValidation': 'send validation',
    'LResetStatus': 'reset',

    //分页
    'LGoto': 'Goto',
    'LPageNum':'Pages Number:',

    //导入列表
    'LImportExpressType': 'Express Type',
    'LImportAll': 'All',
    'LImportCourier':'Courier Express',
    'LImportSend':'Send Express',
    'LImportReturn':'Return Express',
    'LImportExpress':'Import Express',
    'LImportModelDownload':'Download Import Model',
    //新增派宝箱
    'LPakpoboxOperator': 'Operator Id',
    'LPakpoboxName': 'Box Name',
    'LPakpoboxOrderNo': 'OrderNo',
    'LPakpoboxCurrencyUnit': 'Unit',
    'LPakpoboxOverdueType': 'Overdue Tyte',
    'LPakpoboxOverdueTime': 'Overdue Time',
    'LPakpoboxSmsAccount': 'Sms Account',
    'LBoxSize': 'Box Size',
    'LPakpoboxInfoTips': 'Please Confirm infomation',
    'LFormNone': 'Lost Infomation！',

    //派宝箱维护
    'LPakpoboxStatus':'Status' ,
    'LPakpoboxRun':'RUN' ,
    'LPakpoboxStop':'STOP' ,
    'LPakpoboxException':'Exception' ,
    'LPakpoboxOperator':'Operator Num' ,
    'LPakpoboxOperatorName':'Operator Name',
    'LPakpoboxName':'Pakpobox Name',
    'LPakpoboxStatus':'Pakpobox Status',
    'LPakpoboxDetail':'Pakpobox Management',
    'LPakpoboxNew':'+New',
    'LPakpoboxFreeNum': 'Pakpobox Free Num',
    'LPakpoboxNum':'Pakpobox Number',
    'LPakpoBoxDetail': 'Detail',
    'LPakpoBoxColumns': 'Not null columns between the two columns！',
    'LPakpoBoxSubmitRespose': 'Submit Successfullly，Wating ...！',
    'LPakpoBoxSubmitFail': 'Submmit Failed！',
    'LPakpoBoxSubmitBack': 'Confirm To Back！',
    'LPakpoBoxModifyMouthStatus': 'Modidfy Mouth Status',
    'LPakpoBoxEmpty': 'Empty',
    'LPakpoBoxLock': 'Lock',
    'LPakpoBoxFreeMouthNum': 'Free Mouth Num：',
    'LPakpoBoxRemoteUnlock': 'To confirm the following selected case mouth were unlocked remotely？',
    'LPakpoBoxStatusModify': 'To confirm for the following selected mouth state changes？',
    'LPakpoBoxPleaseChooseAMouth': 'Please Choose A Mouth',
    'LPakpoBoxForbiddenBusyStatus': 'Forbid the operator of busy mouth!',
    'LPakpoBoxGetMouthIdFailed': 'Get Mouth Id Failed!',
    'LPakpoBoxFree': 'Free',
    'LPakpoBoxBusy': 'Busy',
    'LPakpoBoxLocked': 'Locked',

    //导入
    'LChooseFile':'Choose File',
    'LBeginUpload':'Upload',
    'LUploadGuide':'Guide',
    'LUploadStep1':'1.First ',
    'LUploadStep12':'，fill in the information according to the example',
    'LUploadStep2':'2. Click select files above, choose the file you want to import',
    'LUploadStep3':'3. Click start uploading, you can upload your files',
    'LWaitingUpload':'Waiting Upload....',
    'LUploading':'Uploading....',
    'LUploadingComplete':'Upload Conplete',
    'LUploadFailId':'Fail Id',
    'LUploadType':'Fail Type',
    'LUploadexisted':'Existed',
    'LUploadNotSure':'Not Sure',
    'LUploadArgError':'Arg Error',
    'LUploadFailCounts':'Records fail，',
    'LUploadFailContent':'Click here to export the failures',
    'LUploadError':'Upload Failed',
    'LStatisticsNameTime': 'Store Time',
    'LStatisticsNameType': 'Store Type',
    'LStatisticsDay1': 'First Day',
    'LStatisticsDay2': 'Second Day',
    'LStatisticsDay3': 'Third Day',
    'LStatisticsDayO': 'Overdue',
    'LStatisticsPer': '%',
    'LStatisticsMINI': 'MINI',
    'LStatisticsS': 'S',
    'LStatisticsM': 'M',
    'LStatisticsL': 'L',
    'LStatisticsXL': 'XL',
    'LStatisticsTotal': 'Combine',
    'LStatisticsExport': 'Import',
    'LPakpoboxEdit': 'Adjust Pakpobox',
    'LPakpoboxRemoteUnlock': 'Remote Unlock',
    'LPakpoboxChangeStatus': 'Modify Status',
    'LPakpoboxMouthId': 'Mouth ID',

    'LWaiting': 'Wait......',
    'LSuccess': 'Successful！',
    'LTips': 'Tips',
    'LStatusError': 'forbid do this for mouth on this status',

    'LTaskCOMMIT': 'Submit Successfully',
    'LTaskSUCCESS': 'Task Successful',
    'LTaskERROR': 'Task Error',


    'LPleaseChoose': 'Please Choose',
    'LNotEmpty': 'Cannot be Empty!',
    'LFormatError': 'Format Error!',
    'LInconformity': 'Inconformity!',
    'LMultiSelected': 'Selected',
    'LMultiSelectedAll': 'All Selected',

    //短信列表
    'LSmsList': 'Message List',
    'LSmsStatus': 'status',
    'LSmsStatusReady': 'Ready',
    'LSmsStatusSuc': 'Success',
    'LSmsStatusFail': 'Failure',
    //广告
    'LBusinessPicChoose': 'Choose Pic...',

    //逾期
    'LOverdueStatus': 'If Overdue',
    'LOverdueStatusYes': 'Yes',
    'LOverdueStatusNo': 'No',
    'LOverdueTimeReset': 'Choose Overdue Time',
    'LResetOverTime' : 'Reset Overdue Time',

    //电商名称
    'LElectronicCommerceName': 'ElectronicCommerceName',
}

module.exports = Lang;